# config/database.yml 
development: 
  adapter: postgresql 
  encoding: utf-8 
  database: miapp_development 
  pool: 5 
  username: miapp 
  password: 
 
test:
  adapter: sqlite3
  database: db/test.sqlite3
  pool: 5
  timeout: 5000

production: 
  adapter: postgresql 
  encoding: utf-8 
  database: miapp_production 
  pool: 5 
  username: miapp 
  password:
